name: Deploy package on tag released

on:
  pull_request:
    branches:
      - dev

jobs:
  bc-compile:
    name: BC compile for release tag
    needs: check-tag
    uses: ./.github/workflows/bc_compile.yaml
    with:
      bc_tag: v0.10.0
    secrets: inherit